const MATERIAIS = [
  { numero: '1', tema: 'Fundamentos da Biologia', arquivos: [
    { nome: '1_Fundamentos da Biologia - introdução e método científico.pptx', tipo: 'slide', url: 'slides/Slides Biologia/1 - Fundamentos da Biologia/1_Fundamentos da Biologia - introdução e método científico.pptx' },
    { nome: '2_Fundamentos da Biologia - reprodução e ciclos de vida.docx', tipo: 'lista', url: 'slides/Slides Biologia/1 - Fundamentos da Biologia/2_Fundamentos da Biologia - reprodução e ciclos de vida.docx' },
    { nome: '2_Fundamentos da Biologia - reprodução e ciclos de vida.pptx', tipo: 'slide', url: 'slides/Slides Biologia/1 - Fundamentos da Biologia/2_Fundamentos da Biologia - reprodução e ciclos de vida.pptx' },
  ] },
  { numero: '2', tema: 'Biomoléculas', arquivos: [
    { nome: '1_Biomoléculas - Introdução, água e sais minerais.docx', tipo: 'lista', url: 'slides/Slides Biologia/2 - Biomoléculas/1_Biomoléculas - Introdução, água e sais minerais.docx' },
    { nome: '1_Biomoléculas - Introdução, água e sais minerais.pptx', tipo: 'slide', url: 'slides/Slides Biologia/2 - Biomoléculas/1_Biomoléculas - Introdução, água e sais minerais.pptx' },
    { nome: '2_Biomoléculas - Carboidratos, lipídios e vitaminas.docx', tipo: 'lista', url: 'slides/Slides Biologia/2 - Biomoléculas/2_Biomoléculas - Carboidratos, lipídios e vitaminas.docx' },
    { nome: '2_Biomoléculas - Carboidratos, lipídios e vitaminas.pptx', tipo: 'slide', url: 'slides/Slides Biologia/2 - Biomoléculas/2_Biomoléculas - Carboidratos, lipídios e vitaminas.pptx' },
    { nome: '3_Biomoléculas - proteínas e ácidos nucleicos.docx', tipo: 'lista', url: 'slides/Slides Biologia/2 - Biomoléculas/3_Biomoléculas - proteínas e ácidos nucleicos.docx' },
    { nome: '3_Biomoléculas - proteínas e ácidos nucleicos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/2 - Biomoléculas/3_Biomoléculas - proteínas e ácidos nucleicos.pptx' },
  ] },
  { numero: '3', tema: 'Citologia', arquivos: [
    { nome: '1_Citologia - introdução, membrana e transporte.docx', tipo: 'lista', url: 'slides/Slides Biologia/3 - Citologia/1_Citologia - introdução, membrana e transporte.docx' },
    { nome: '1_Citologia - introdução, membrana e transporte.pptx', tipo: 'slide', url: 'slides/Slides Biologia/3 - Citologia/1_Citologia - introdução, membrana e transporte.pptx' },
    { nome: '2_Citologia - citoplasma e organelas.docx', tipo: 'lista', url: 'slides/Slides Biologia/3 - Citologia/2_Citologia - citoplasma e organelas.docx' },
    { nome: '2_Citologia - citoplasma e organelas.pptx', tipo: 'slide', url: 'slides/Slides Biologia/3 - Citologia/2_Citologia - citoplasma e organelas.pptx' },
    { nome: '3_Citologia - metabolismo energetico - respiração celular e fermentação.docx', tipo: 'lista', url: 'slides/Slides Biologia/3 - Citologia/3_Citologia - metabolismo energetico - respiração celular e fermentação.docx' },
    { nome: '3_Citologia - metabolismo energetico - respiração celular e fermentação.pptx', tipo: 'slide', url: 'slides/Slides Biologia/3 - Citologia/3_Citologia - metabolismo energetico - respiração celular e fermentação.pptx' },
    { nome: '4_Citologia - metabolismo energetico - fotossíntese e quimiossíntese.docx', tipo: 'lista', url: 'slides/Slides Biologia/3 - Citologia/4_Citologia - metabolismo energetico - fotossíntese e quimiossíntese.docx' },
    { nome: '4_Citologia - metabolismo energetico - fotossíntese e quimiossíntese.pptx', tipo: 'slide', url: 'slides/Slides Biologia/3 - Citologia/4_Citologia - metabolismo energetico - fotossíntese e quimiossíntese.pptx' },
  ] },
  { numero: '4', tema: 'Núcleo', arquivos: [
    { nome: '1_Núcleo - características, cromossomos e mutações.docx', tipo: 'lista', url: 'slides/Slides Biologia/4 - Núcleo/1_Núcleo - características, cromossomos e mutações.docx' },
    { nome: '1_Núcleo - características, cromossomos e mutações.pptx', tipo: 'slide', url: 'slides/Slides Biologia/4 - Núcleo/1_Núcleo - características, cromossomos e mutações.pptx' },
    { nome: '2_Núcleo - dogma central da biologia - duplicação, transcrição e tradução.docx', tipo: 'lista', url: 'slides/Slides Biologia/4 - Núcleo/2_Núcleo - dogma central da biologia - duplicação, transcrição e tradução.docx' },
    { nome: '2_Núcleo - dogma central da biologia - duplicação, transcrição e tradução.pptx', tipo: 'slide', url: 'slides/Slides Biologia/4 - Núcleo/2_Núcleo - dogma central da biologia - duplicação, transcrição e tradução.pptx' },
    { nome: '3_Núcleo - Ciclo Celular e Divisão Celular.docx', tipo: 'lista', url: 'slides/Slides Biologia/4 - Núcleo/3_Núcleo - Ciclo Celular e Divisão Celular.docx' },
    { nome: '3_Núcleo - Ciclo Celular e Divisão Celular.pptx', tipo: 'slide', url: 'slides/Slides Biologia/4 - Núcleo/3_Núcleo - Ciclo Celular e Divisão Celular.pptx' },
  ] },
  { numero: '5', tema: 'Genética', arquivos: [
    { nome: '1_Genética - introdução e primeira lei de mendel.docx', tipo: 'lista', url: 'slides/Slides Biologia/5 - Genética/1_Genética - introdução e primeira lei de mendel.docx' },
    { nome: '1_Genética - introdução e primeira lei de mendel.pptx', tipo: 'slide', url: 'slides/Slides Biologia/5 - Genética/1_Genética - introdução e primeira lei de mendel.pptx' },
    { nome: '1_Genética - introdução e primeira lei de mendel-sem gabarito.docx', tipo: 'lista', url: 'slides/Slides Biologia/5 - Genética/1_Genética - introdução e primeira lei de mendel-sem gabarito.docx' },
    { nome: '2_Genética - Polialelia, Genética do Sangue e herança sexual e Segunda lei de Mendel.docx', tipo: 'lista', url: 'slides/Slides Biologia/5 - Genética/2_Genética - Polialelia, Genética do Sangue e herança sexual e Segunda lei de Mendel.docx' },
    { nome: '2_Genética - Polialelia, Genética do Sangue e herança sexual e Segunda lei de Mendel.pptx', tipo: 'slide', url: 'slides/Slides Biologia/5 - Genética/2_Genética - Polialelia, Genética do Sangue e herança sexual e Segunda lei de Mendel.pptx' },
    { nome: '3_Genética - Interação Gênica, Genética de Populações e Linkage.pptx', tipo: 'slide', url: 'slides/Slides Biologia/5 - Genética/3_Genética - Interação Gênica, Genética de Populações e Linkage.pptx' },
    { nome: '4 e 5_Genética - Interação Gênica, Genética de Populações e Linkage.docx', tipo: 'lista', url: 'slides/Slides Biologia/5 - Genética/4 e 5_Genética - Interação Gênica, Genética de Populações e Linkage.docx' },
    { nome: 'Genética Lista Extra.docx', tipo: 'lista', url: 'slides/Slides Biologia/5 - Genética/Genética Lista Extra.docx' },
  ] },
  { numero: '6', tema: 'Biotecnologia', arquivos: [
    { nome: '1_Biotecnologia - introdução, células tronco e clonagem.pptx', tipo: 'slide', url: 'slides/Slides Biologia/6 - Biotecnologia/1_Biotecnologia - introdução, células tronco e clonagem.pptx' },
    { nome: '2_Biotecnologia - transgenia, dna fingerprint e outras técnicas.pptx', tipo: 'slide', url: 'slides/Slides Biologia/6 - Biotecnologia/2_Biotecnologia - transgenia, dna fingerprint e outras técnicas.pptx' },
    { nome: 'Exercícios_Biotecnologia.docx', tipo: 'lista', url: 'slides/Slides Biologia/6 - Biotecnologia/Exercícios_Biotecnologia.docx' },
  ] },
  { numero: '7', tema: 'Origem da Vida e Evolução', arquivos: [
    { nome: '1_Origem da Vida.docx', tipo: 'lista', url: 'slides/Slides Biologia/7 - Origem da Vida e Evolução/1_Origem da Vida.docx' },
    { nome: '1_Origem da Vida.pptx', tipo: 'slide', url: 'slides/Slides Biologia/7 - Origem da Vida e Evolução/1_Origem da Vida.pptx' },
    { nome: '2_Evolução - Introdução e teorias evolutivas.pptx', tipo: 'slide', url: 'slides/Slides Biologia/7 - Origem da Vida e Evolução/2_Evolução - Introdução e teorias evolutivas.pptx' },
    { nome: '3_Evolução -Teoria Sintética, Especiação.pptx', tipo: 'slide', url: 'slides/Slides Biologia/7 - Origem da Vida e Evolução/3_Evolução -Teoria Sintética, Especiação.pptx' },
    { nome: 'Evolução.docx', tipo: 'lista', url: 'slides/Slides Biologia/7 - Origem da Vida e Evolução/Evolução.docx' },
    { nome: 'gabarito 1_Origem da Vida.docx', tipo: 'lista', url: 'slides/Slides Biologia/7 - Origem da Vida e Evolução/gabarito 1_Origem da Vida.docx' },
  ] },
  { numero: '8', tema: 'Classificação e Pequenos Reinos', arquivos: [
    { nome: '1_Classificação Biológica.docx', tipo: 'lista', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/1_Classificação Biológica.docx' },
    { nome: '1_Classificação Biológica.pptx', tipo: 'slide', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/1_Classificação Biológica.pptx' },
    { nome: '2_Classificação Biológica - Vírus e viroses.docx', tipo: 'lista', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/2_Classificação Biológica - Vírus e viroses.docx' },
    { nome: '2_Classificação Biológica - Vírus e viroses.pptx', tipo: 'slide', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/2_Classificação Biológica - Vírus e viroses.pptx' },
    { nome: '3_Classificação Biológica - Bactérias e Bacterioses.docx', tipo: 'lista', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/3_Classificação Biológica - Bactérias e Bacterioses.docx' },
    { nome: '3_Classificação Biológica - Bactérias e Bacterioses.pptx', tipo: 'slide', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/3_Classificação Biológica - Bactérias e Bacterioses.pptx' },
    { nome: '4_Classificação Biológica - Protozoários.docx', tipo: 'lista', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/4_Classificação Biológica - Protozoários.docx' },
    { nome: '4_Classificação Biológica - Protozoários.pptx', tipo: 'slide', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/4_Classificação Biológica - Protozoários.pptx' },
    { nome: '5_Classificação Biológica - Algas e Fungos.docx', tipo: 'lista', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/5_Classificação Biológica - Algas e Fungos.docx' },
    { nome: '5_Classificação Biológica - Algas e Fungos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/8 - Classificação e Pequenos Reinos/5_Classificação Biológica - Algas e Fungos.pptx' },
  ] },
  { numero: '9', tema: 'Reino Animal', arquivos: [
    { nome: '1_Reino Animal - Poríferos, Cnidários e Platelmintos.docx', tipo: 'lista', url: 'slides/Slides Biologia/9 - Reino Animal/1_Reino Animal - Poríferos, Cnidários e Platelmintos.docx' },
    { nome: '1_Reino Animal - Poríferos, Cnidários e Platelmintos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/9 - Reino Animal/1_Reino Animal - Poríferos, Cnidários e Platelmintos.pptx' },
    { nome: '2_Reino Animal - Nematelmintos, Moluscos e Anelídeos.docx', tipo: 'lista', url: 'slides/Slides Biologia/9 - Reino Animal/2_Reino Animal - Nematelmintos, Moluscos e Anelídeos.docx' },
    { nome: '2_Reino Animal - Nematelmintos, Moluscos e Anelídeos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/9 - Reino Animal/2_Reino Animal - Nematelmintos, Moluscos e Anelídeos.pptx' },
    { nome: '3_Reino Animal - Artrópodes e Equinodermos.docx', tipo: 'lista', url: 'slides/Slides Biologia/9 - Reino Animal/3_Reino Animal - Artrópodes e Equinodermos.docx' },
    { nome: '3_Reino Animal - Artrópodes e Equinodermos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/9 - Reino Animal/3_Reino Animal - Artrópodes e Equinodermos.pptx' },
    { nome: '4_Reino Animal - Cordados - introdução, peixes e anfíbios.docx', tipo: 'lista', url: 'slides/Slides Biologia/9 - Reino Animal/4_Reino Animal - Cordados - introdução, peixes e anfíbios.docx' },
    { nome: '4_Reino Animal - Cordados - introdução, peixes e anfíbios.pptx', tipo: 'slide', url: 'slides/Slides Biologia/9 - Reino Animal/4_Reino Animal - Cordados - introdução, peixes e anfíbios.pptx' },
    { nome: '5_Reino Animal - Cordados - répteis, aves e mamíferos.docx', tipo: 'lista', url: 'slides/Slides Biologia/9 - Reino Animal/5_Reino Animal - Cordados - répteis, aves e mamíferos.docx' },
    { nome: '5_Reino Animal - Cordados - répteis, aves e mamíferos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/9 - Reino Animal/5_Reino Animal - Cordados - répteis, aves e mamíferos.pptx' },
    { nome: 'Lista Extra - Cordados (todos os grupos).docx', tipo: 'lista', url: 'slides/Slides Biologia/9 - Reino Animal/Lista Extra - Cordados (todos os grupos).docx' },
  ] },
  { numero: '10', tema: 'Histologia Animal', arquivos: [
    { nome: '1_Histologia Animal - Tecido Epitelial e Conjuntivo.docx', tipo: 'lista', url: 'slides/Slides Biologia/10 - Histologia Animal/1_Histologia Animal - Tecido Epitelial e Conjuntivo.docx' },
    { nome: '1_Histologia Animal - Tecido Epitelial e Conjuntivo.pptx', tipo: 'slide', url: 'slides/Slides Biologia/10 - Histologia Animal/1_Histologia Animal - Tecido Epitelial e Conjuntivo.pptx' },
    { nome: '2_Histologia Animal - Tecido Muscular e Nervoso.docx', tipo: 'lista', url: 'slides/Slides Biologia/10 - Histologia Animal/2_Histologia Animal - Tecido Muscular e Nervoso.docx' },
    { nome: '2_Histologia Animal - Tecido Muscular e Nervoso.pptx', tipo: 'slide', url: 'slides/Slides Biologia/10 - Histologia Animal/2_Histologia Animal - Tecido Muscular e Nervoso.pptx' },
  ] },
  { numero: '11', tema: 'Fisiologia Humana', arquivos: [
    { nome: '1_Fisiologia Humana - Sistema Digestório.docx', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/1_Fisiologia Humana - Sistema Digestório.docx' },
    { nome: '1_Fisiologia Humana - Sistema Digestório.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/1_Fisiologia Humana - Sistema Digestório.pptx' },
    { nome: '10_Fisiologia Humana - Órgãos genitais, ciclo menstrual, fecundação e gêmeos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/10_Fisiologia Humana - Órgãos genitais, ciclo menstrual, fecundação e gêmeos.pptx' },
    { nome: '2_Fisiologia Humana - Sistema Respiratório.docx', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/2_Fisiologia Humana - Sistema Respiratório.docx' },
    { nome: '2_Fisiologia Humana - Sistema Respiratório.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/2_Fisiologia Humana - Sistema Respiratório.pptx' },
    { nome: '3_Fisiologia Humana - Sistema Circulatório.docx', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/3_Fisiologia Humana - Sistema Circulatório.docx' },
    { nome: '3_Fisiologia Humana - Sistema Circulatório.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/3_Fisiologia Humana - Sistema Circulatório.pptx' },
    { nome: '4_Fisiologia Humana - Sistema Urinário.docx', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/4_Fisiologia Humana - Sistema Urinário.docx' },
    { nome: '4_Fisiologia Humana - Sistema Urinário.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/4_Fisiologia Humana - Sistema Urinário.pptx' },
    { nome: '5_Fisiologia Humana - Sistema Nervoso.docx', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/5_Fisiologia Humana - Sistema Nervoso.docx' },
    { nome: '5_Fisiologia Humana - Sistema Nervoso.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/5_Fisiologia Humana - Sistema Nervoso.pptx' },
    { nome: '6_Fisiologia Humana - Sistema Endócrino.docx', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/6_Fisiologia Humana - Sistema Endócrino.docx' },
    { nome: '6_Fisiologia Humana - Sistema Endócrino.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/6_Fisiologia Humana - Sistema Endócrino.pptx' },
    { nome: '7_Fisiologia Humana - Sistema Sensorial.dot', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/7_Fisiologia Humana - Sistema Sensorial.dot' },
    { nome: '7_Fisiologia Humana - Sistema Sensorial.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/7_Fisiologia Humana - Sistema Sensorial.pptx' },
    { nome: '8_Fisiologia Humana - Sistema Imunológico.docx', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/8_Fisiologia Humana - Sistema Imunológico.docx' },
    { nome: '8_Fisiologia Humana - Sistema Imunológico.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/8_Fisiologia Humana - Sistema Imunológico.pptx' },
    { nome: '9_10_Exercícios Sistema e Aparelho Genital, Método Contraceptivos, Ciclo Menstrual e Gametogênese.docx', tipo: 'lista', url: 'slides/Slides Biologia/11 - Fisiologia Humana/9_10_Exercícios Sistema e Aparelho Genital, Método Contraceptivos, Ciclo Menstrual e Gametogênese.docx' },
    { nome: '9_Fisiologia Humana - Aparelhos Reprodutores, Gametogênese e Métodos Contraceptivos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/11 - Fisiologia Humana/9_Fisiologia Humana - Aparelhos Reprodutores, Gametogênese e Métodos Contraceptivos.pptx' },
  ] },
  { numero: '12', tema: 'Embriologia', arquivos: [
    { nome: 'Embriologia Humana.pptx', tipo: 'slide', url: 'slides/Slides Biologia/12 - Embriologia/Embriologia Humana.pptx' },
    { nome: 'Exercícios Embriologia.docx', tipo: 'lista', url: 'slides/Slides Biologia/12 - Embriologia/Exercícios Embriologia.docx' },
  ] },
  { numero: '13', tema: 'Botânica', arquivos: [
    { nome: '1 e 2_ Grupos Vegetais.docx', tipo: 'lista', url: 'slides/Slides Biologia/13 - Botânica/1 e 2_ Grupos Vegetais.docx' },
    { nome: '1_Grupos Vegetais - introdução, briófitas e pteridófitas.pptx', tipo: 'slide', url: 'slides/Slides Biologia/13 - Botânica/1_Grupos Vegetais - introdução, briófitas e pteridófitas.pptx' },
    { nome: '2_Grupos Vegetais - gimnospermas e angiospermas.pptx', tipo: 'slide', url: 'slides/Slides Biologia/13 - Botânica/2_Grupos Vegetais - gimnospermas e angiospermas.pptx' },
    { nome: '3 e 4_ Histologia e Organologia Vegetal.docx', tipo: 'lista', url: 'slides/Slides Biologia/13 - Botânica/3 e 4_ Histologia e Organologia Vegetal.docx' },
    { nome: '3_Histologia Vegetal.pptx', tipo: 'slide', url: 'slides/Slides Biologia/13 - Botânica/3_Histologia Vegetal.pptx' },
    { nome: '4_Organologia Vegetal.pptx', tipo: 'slide', url: 'slides/Slides Biologia/13 - Botânica/4_Organologia Vegetal.pptx' },
    { nome: '5_Fisiologia Vegetal.docx', tipo: 'lista', url: 'slides/Slides Biologia/13 - Botânica/5_Fisiologia Vegetal.docx' },
    { nome: '5_Fisiologia Vegetal.pptx', tipo: 'slide', url: 'slides/Slides Biologia/13 - Botânica/5_Fisiologia Vegetal.pptx' },
  ] },
  { numero: '14', tema: 'Ecologia', arquivos: [
    { nome: '1_Ecologia - conceitos, relações e sucessão ecológicas, ciclos biogeoquímicos.docx', tipo: 'lista', url: 'slides/Slides Biologia/14 - Ecologia/1_Ecologia - conceitos, relações e sucessão ecológicas, ciclos biogeoquímicos.docx' },
    { nome: '1_Ecologia - conceitos, relações e sucessão ecológicas, ciclos biogeoquímicos.pptx', tipo: 'slide', url: 'slides/Slides Biologia/14 - Ecologia/1_Ecologia - conceitos, relações e sucessão ecológicas, ciclos biogeoquímicos.pptx' },
    { nome: '2_Ecologia - Cadeias e Teias Alimentares.docx', tipo: 'lista', url: 'slides/Slides Biologia/14 - Ecologia/2_Ecologia - Cadeias e Teias Alimentares.docx' },
    { nome: '2_Ecologia - Cadeias e Teias Alimentares.pptx', tipo: 'slide', url: 'slides/Slides Biologia/14 - Ecologia/2_Ecologia - Cadeias e Teias Alimentares.pptx' },
    { nome: '3_Ecologia - Biomas Brasileiros.docx', tipo: 'lista', url: 'slides/Slides Biologia/14 - Ecologia/3_Ecologia - Biomas Brasileiros.docx' },
    { nome: '3_Ecologia - Biomas Brasileiros.pptx', tipo: 'slide', url: 'slides/Slides Biologia/14 - Ecologia/3_Ecologia - Biomas Brasileiros.pptx' },
    { nome: '4_Ecologia - Problemas Ambientais I - introdução e lixo.pptx', tipo: 'slide', url: 'slides/Slides Biologia/14 - Ecologia/4_Ecologia - Problemas Ambientais I - introdução e lixo.pptx' },
    { nome: '5_Ecologia - Problemas Ambientais II - mineração e agricultura.pptx', tipo: 'slide', url: 'slides/Slides Biologia/14 - Ecologia/5_Ecologia - Problemas Ambientais II - mineração e agricultura.pptx' },
    { nome: '6_Ecologia - Problemas Ambientais III - pecuária e poluição atmosférica.pptx', tipo: 'slide', url: 'slides/Slides Biologia/14 - Ecologia/6_Ecologia - Problemas Ambientais III - pecuária e poluição atmosférica.pptx' },
    { nome: '7_Ecologia - Problemas Ambientais IV - poluição hídrica e perda de biodiversidade.pptx', tipo: 'slide', url: 'slides/Slides Biologia/14 - Ecologia/7_Ecologia - Problemas Ambientais IV - poluição hídrica e perda de biodiversidade.pptx' },
    { nome: 'Problemas Ambientais.docx', tipo: 'lista', url: 'slides/Slides Biologia/14 - Ecologia/Problemas Ambientais.docx' },
  ] },
];
